#!/bin/bash
WD=$PWD
rm -rf /root/xtream-ui-ubuntu20.04
git clone git@github.com:amidevous/xtream-ui-ubuntu20.04.git /root/xtream-ui-ubuntu20.04
reprepro --keepunreferencedfiles -Vb /root/xtream-ui-ubuntu20.04/package/Ubuntu/ includedeb jammy $1
cp /root/xtream-ui-ubuntu20.04/package/Ubuntu/dists/jammy/Release /root/xtream-ui-ubuntu20.04/package/Ubuntu/dists/jammy/InRelease
cd /root/xtream-ui-ubuntu20.04/
git add *
git commit -m "add Ubuntu 22.04 packages"
git push -u origin master
cd $WD
rm -f $1
